version: '3.3'
services:
  redis:
    image: redis:latest
    hostname: redis
  web:
    build:
      context: .
      dockerfile: Dockerfile
    hostname: web
    command: flask run --port 8000 --host=0.0.0.0
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    links:
      - redis
  worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A celery_worker.celery worker --pool=solo --loglevel=info
    environment:
        CELERY_BROKER_URL: redis://redis:6379/0
        RESULT_BACKEND: redis://redis:6379/0
    volumes:
      - .:/app
    links:
      - redis
    depends_on:
      - redis
  beat:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A celery_worker.celery beat --loglevel=info
    environment:
        CELERY_BROKER_URL: redis://redis:6379/0
        RESULT_BACKEND: redis://redis:6379/0
    volumes:
      - .:/app
    links:
      - redis
    depends_on:
      - redis
  monitor:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A celery_worker.celery flower --address=0.0.0.0 --port=8001
    ports:
     - "8001:8001"
    environment:
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
    depends_on:
      - redis
      - worker
    volumes:
      - .:/app
